# https://qiita.com/uryyyyyyy/items/06f32d1b979e48944947
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-persistent-storage-claim
spec:
  storageClassName: "mongo-sc"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30G
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongo-sc
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  serviceName: "mongo-service"
  template:
    metadata:
      labels:
        app: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: mongo:4.4
        imagePullPolicy: "IfNotPresent"
        resources:
          limits:
            cpu: 25m
            memory: 100Mi #1500m
          requests:
            cpu: 25m
            memory: 100Mi #1500m
        # command:
        #   - mongod
        #   - "--replSet"
        #   - rs0
        #   - "--bind_ip"
        #   - "0.0.0.0"
        ports:
          - containerPort: 27017  
        # envFrom:
        # - configMapRef:
        #     name: postgres-configuration
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
          # subPath: data
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-persistent-storage-claim